name: Build
on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all --check

  build-desktop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt-get install -y libsdl2-dev libsdl2-image-dev
      - run: cargo build --release

  build-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt-get install -y binaryen
      - run: cargo install wasm-bindgen-cli
      - run: ./build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: web/dist

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [build-web]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
      - id: deployment
        uses: actions/deploy-pages@v2
